#!/bin/bash
if test "$#" != 1; then 
  echo "usage: alert [alertname]"
  echo "add a todo item into my todo file and highlights the tmux window's title."
  exit
fi
if ! egrep -q "^#$1\b" "$HOME/todo"; then
  echo "#$1" >>"$HOME/todo"
fi
hi alert
