#!/bin/bash

# early exit if possible.
if test -z "$(ls -A /homebufrw)"; then
  echo nothing to sync.
  exit
fi

# lock.
if ! test -f /tmp/.bsync.lock; then
  touch /tmp/.bsync.lock
fi
exec 3</tmp/.bsync.lock
flock 3

# sync.
wmount disk || exit
usync /homebufrw /homedisk
wmount buf
