#!/bin/bash

# difix: display fixer.
# if a display is connected and it's not turned on, difix switches to it.
# otherwise it switches back to the laptop screen.

xr="$(xrandr 2>&1)"
display="$(echo "$xr" | sed -En 's/^(DP-.) connected.*/\1/p')"
displayres="$(echo "$xr" | sed -En "/^$display connected/,/^[A-Z]/{/\*/p}")"
laptop="$(echo "$xr" | sed -En 's/^(LVDS..|eDP..) connected.*/\1/p')"
laptoppref="$(echo "$xr" | sed -En "/^$laptop connected/,/^[A-Z]/{/1920x1200/p}")"

if test -n "$display" && test -z "$displayres"; then
  # if display is connected but not turned on, switch to it.
  xrandr --output "$display" --auto
  xrandr --output "$laptop" --off
  sleep 2
  setxkbmap -option caps:escape
  rx  # reset the x settings.
else
  # set the laptop screen in every other case.
  # turn off the display if it was on.
  if test -n "$laptoppref"; then
    xrandr --output "$laptop" --mode 1920x1200
  else
    xrandr --output "$laptop" --auto
  fi
  xrandr --output "$display" --off
fi
