#!/bin/bash
# reset x settings to reasonable defaults.
if test "$HOSTNAME" = ipi; then
  xsetroot -solid '#ffffff'
else
  xsetroot -solid '#000'
fi
xsetroot -cursor_name arrow
xset r rate 300 40
xset s off
xset -dpms
if test "$HOSTNAME" != ipi; then
  # enable screensaving on all my machines.
  xset s noblank
  xset s 900
  xset dpms 915 915 915
  x11lock stop >/dev/null
  x11lock start
fi
xset +fp ~/.fonts
xrdb ~/.Xdefaults
xmodmap ~/.xmodmap
