#!/bin/bash
if test "$#" -ge 2 || test "$1" = -h || test "$1" = --help; then
  echo 'usage: ta [hostname]'
  echo 'run tmux attach on a remote host.'
  echo 'attach locally when running without args.'
  exit
fi
if test "$#" -eq 0; then
  tmux attach
  exit
fi
ssh -t -X -Y "$1" 'export LANG=en_US.UTF-8; tmux attach || start_env'
