#!/bin/bash

# verify that chrome still has this feature.
url=https://chromium.googlesource.com/chromium/src/+/main/components/omnibox/browser/omnibox_field_trial.cc?format=TEXT
pattern=UIMaxAutocompleteMatchesByProvider
if ! curl $url 2>/dev/null | base64 -d | grep -q $pattern; then
  # if this triggers then maybe talk to the chrome folks?
  echo "xchrome-fail" >/tmp/.sysstatmsg
fi

# start chrome with no autocompletion in its omnibox.
google-chrome \
  --enable-features="OmniboxUIExperimentMaxAutocompleteMatches<Trial" \
  --force-fieldtrials="Trial/Group" \
  --force-fieldtrial-params="Trial.Group:UIMaxAutocompleteMatches/1/UIMaxAutocompleteMatchesByProvider/*%3A0" \
  --force-prefers-reduced-motion \
  "$@"
