#!/bin/bash

echo -e '\e[37mJust enter your youtube links one per line:\e[0m'
cat | xargs -n1 -P8 yt-dlp -f 22 --no-part --no-playlist --no-progress | \
sed -e $'s/^\\[download\\] Destination: .*/\e[33m&\e[0m/' \
    -e $'s/^\\[.*/\e[37m&\e[0m/'
